In [24]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # For creating plots
import matplotlib.ticker as mtick # For specifying the axes tick format 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib
import os
print(os.listdir("../"))

['Data_Acquisition_and_Understanding', '.DS_Store', 'Modeling', 'Readme.md', 'Deployment']

In [2]:
df = pd.read_csv('../../Sample_Data/Raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# Checking the data types of all the columns
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [8]:
# Drop any columns not needed for prediction
df2 = df.drop(['customerID'], axis=1)

In [9]:
# Drop missing values if any
df2 = df2.dropna()

In [10]:
# Converting Total Charges to a numerical data type.
df2.TotalCharges = pd.to_numeric(df2.TotalCharges, errors='coerce')

In [11]:
#Convertin the churn results into a binary numeric variable
df2['Churn'].replace(to_replace='Yes', value=1, inplace=True)
df2['Churn'].replace(to_replace='No',  value=0, inplace=True)

In [12]:
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [13]:
# Convert categorical columns to numerical using one-hot encoding
df3 = pd.get_dummies(df2, drop_first=True)
df3.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [16]:
# Split the data into features and target variable
X = df3.drop('Churn', axis=1)
Y = df3['Churn']

In [21]:
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=100)

In [26]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a logistic regression model
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [29]:
# Evaluate the model
Y_pred = model.predict(X_test)
print(f'Accuracy: {accuracy_score(Y_test, Y_pred)}')
print(classification_report(Y_test, Y_pred))

Accuracy: 0.7882018479033405
              precision    recall  f1-score   support

           0       0.84      0.87      0.86      1013
           1       0.64      0.57      0.60       394

    accuracy                           0.79      1407
   macro avg       0.74      0.72      0.73      1407
weighted avg       0.78      0.79      0.78      1407

In [30]:
# Save the model and scaler to disk
joblib.dump(model, 'churn_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [31]:
from flask import Flask, request, jsonify, render_template
import joblib
import numpy as np

app = Flask(__name__)

# Load the trained model and scaler
model = joblib.load('churn_model.pkl')
scaler = joblib.load('scaler.pkl')

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    # Get data from form
    data = request.form.to_dict()
    data = [float(data[key]) for key in data]

    # Convert data to numpy array and scale
    data = np.array(data).reshape(1, -1)
    data = scaler.transform(data)

    # Make prediction
    prediction = model.predict(data)
    output = 'Yes' if prediction[0] == 1 else 'No'

    return render_template('index.html', prediction_text=f'Customer Churn Prediction: {output}')

if __name__ == "__main__":
    app.run(debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with watchdog (fsevents)
Traceback (most recent call last):
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 22, in <module>
    from IPython.core.application import (
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/IPython/__init__.py", line 52, in <module>
    from .terminal.embed import embed
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 46, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/IPython/core/completer.py", line 149, in <module>
    import jedi
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/jedi/__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, preload_module
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/jedi/api/__init__.py", line 13, in <module>
    import parso
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/parso/__init__.py", line 42, in <module>
    from parso.grammar import Grammar, load_grammar
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/parso/grammar.py", line 13, in <module>
    from parso.cache import parser_cache, load_module, try_to_save_module
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/parso/cache.py", line 76, in <module>
    _default_cache_path = _get_default_cache_path()
  File "/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/parso/cache.py", line 73, in _get_default_cache_path
    return dir_.expanduser()
AttributeError: 'PosixPath' object has no attribute 'expanduser'

SystemExit: 1

/Users/hanhan/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)